import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { EdgeStoreProvider } from '@/lib/edgestore';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Flat Shares',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <Toaster position="top-center" />
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
