import type { Metadata } from 'next';
import FooterPage from './_components/shared/footer';
import Navbar from './_components/shared/Navbar';

export const metadata: Metadata = {
  title: 'Flat Shares',
  description: 'Generated by create next app',
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto md:container">
      <Navbar />
      {children}
      <FooterPage />
    </div>
  );
}
